// src/constants/metodo.js

export const CONCEITOS_METODO = [
  {
    id: "pretest",
    titulo: "Pré-teste",
    l1: "Resolver 3 a 5 questões sobre o tema ANTES de qualquer teoria ativa o cérebro e mapeia lacunas reais.",
    l2: [
      "Abra sua plataforma de questões e busque pelo tema do dia.",
      "Resolva de 3 a 5 questões de forma direta, sem consultar material de apoio.",
      "Não se preocupe com erros: o foco é ativação cerebral e mapeamento de lacunas.",
      "Observe os termos técnicos e os focos de cobrança das questões.",
    ],
    l3: "O cérebro consolida melhor após criar ganchos cognitivos prévios. Errar antes de estudar aumenta a absorção dos pontos críticos durante a leitura subsequente (Efeito Pré-Teste: d = 0.73, Roediger & Karpicke 2006).",
    ctaLabel: "Ver Academia do Método",
    ctaTarget: "academia",
  },
  {
    id: "leitura",
    titulo: "Leitura Ativa",
    l1: "Estude em blocos pequenos intercalados com recuperação ativa imediata — nunca leitura passiva de grandes volumes.",
    l2: [
      "Defina uma pergunta-missão (ex: 'O que define a conduta no trauma torácico?').",
      "Leia um bloco pequeno de conteúdo (8–12 páginas ou 15 minutos de aula).",
      "Feche o material completamente.",
      "Escreva em 2–3 linhas o que você acabou de reter (mini brain dump).",
      "Reabra e destaque apenas o que você esqueceu no dump.",
    ],
    l3: "O esforço de fechar o livro e tentar lembrar (free recall) sinaliza ao hipocampo que aquela informação é vital, reduzindo a curva de esquecimento em mais de 50%.",
    ctaLabel: "Ver Academia do Método",
    ctaTarget: "academia",
  },
  {
    id: "esqueleto",
    titulo: "Esqueleto Mental",
    l1: "Construir a estrutura lógica do assunto de cabeça antes de consultar o material cria esquemas de memória organizados e duráveis.",
    l2: [
      "Mantenha os livros e resumos fechados.",
      "Esboce a hierarquia do tema no papel (Causas, Sintomas, Diagnóstico, Conduta, Complicações).",
      "Foque na árvore de conexões, não nos detalhes finos.",
      "Abra o material e conecte os detalhes nos galhos corretos.",
    ],
    l3: "Organizar conceitos em árvore lógica (schema theory) reduz a carga de memória de trabalho e facilita a recuperação sob pressão.",
    ctaLabel: "Ver Academia do Método",
    ctaTarget: "academia",
  },
  {
    id: "braindump",
    titulo: "Brain Dump Final",
    l1: "Escreva tudo que lembra sobre um tema em folha em branco com limite rígido de 3 minutos — é a prática de recuperação mais potente.",
    l2: [
      "Marque 3 minutos no cronômetro.",
      "Com materiais fechados, escreva o máximo de detalhes, fórmulas ou condutas clínicas possíveis.",
      "Escreva de forma desordenada e rápida: o esforço é o que importa.",
      "Ao final, use uma caneta de cor diferente para preencher o que ficou em branco.",
    ],
    l3: "O esforço extremo de recuperação sem pistas é o maior impulsionador da consolidação de longo prazo (Testing Effect: d = 0.74, Roediger & Karpicke).",
    ctaLabel: "Ver Academia do Método",
    ctaTarget: "academia",
  },
  {
    id: "questoes",
    titulo: "Questões e Diagnóstico",
    l1: "Resolver questões sem analisar os erros individualmente é metade do trabalho — a análise de causa é o que converte erro em acerto futuro.",
    l2: [
      "Resolva blocos de 15–20 questões do tema de forma ininterrupta.",
      "Corrija todas de uma vez ao final.",
      "Para cada erro, classifique a causa real: lacuna de conteúdo, raciocínio ou descuido.",
      "Use as causas para criar flashcards específicos e direcionar o próximo estudo.",
    ],
    l3: "Resolver questões é a melhor simulação de transferência de aprendizado. Análise sistemática dos erros previne padrões incorretos e calibra o viés metacognitivo.",
    ctaLabel: "Registrar sessão de simulado",
    ctaTarget: "sims",
  },
  {
    id: "anki",
    titulo: "Flashcards Espaçados",
    l1: "Criar cartões atômicos e revisá-los pelo FSRS é mais eficiente que qualquer releitura — o intervalo certo mantém a memória com mínimo esforço.",
    l2: [
      "Crie cartões com apenas 1 fato isolado por cartão (Princípio da Atomicidade).",
      "Use omissão de palavras (cloze) ou perguntas diretas com resposta de 1 linha.",
      "Adicione contexto clínico para dar significado ao fato.",
      "Revise diariamente seguindo as datas propostas pelo algoritmo.",
    ],
    l3: "A repetição espaçada otimiza o tempo revisando no momento exato em que o cérebro está prestes a esquecer, fortalecendo conexões sinápticas com eficiência máxima (FSRS Algorithm).",
    ctaLabel: "Abrir Anki Audit",
    ctaTarget: "anki",
  },
  {
    id: "revisao_espacada",
    titulo: "Por que D1, D4, D7, D21?",
    l1: "O esquema de revisão no Dia 1, 4, 7 e 21 é baseado na curva de esquecimento — cada revisão no momento certo dobra o intervalo de retenção.",
    l2: [
      "D1: consolida a memória de curto prazo antes que o tema esfrie.",
      "D4: reativa antes do esquecimento crítico (70–80% de retenção).",
      "D7: revisão de diferencial — reforce o que separa esse tema dos próximos.",
      "D21: mini-caso ou teste cloze — verifica transferência de longo prazo.",
    ],
    l3: "Revisão distribuída (distributed practice) melhora a retenção em 30–50% vs. releitura massed. O esforço de busca da memória (retrieval effort) fortalece o engrama neural a cada sessão.",
    ctaLabel: "Abrir Plano",
    ctaTarget: "crono",
  },
  {
    id: "interleaving",
    titulo: "Misture as Áreas",
    l1: "Estudar uma área por semana inteira (blocked practice) é confortável mas menos eficaz — misturar áreas força discriminação e melhora a transferência.",
    l2: [
      "Quando possível, intercale 2–3 matérias diferentes no mesmo dia de estudo.",
      "A sensação de dificuldade maior é o sinal de que está funcionando.",
      "No MedRev, o plano já tenta distribuir áreas por semana — respeite essa distribuição.",
      "Reserve 1 área por tempo maior apenas se houver deficit crítico detectado.",
    ],
    l3: "Interleaving reduz a ilusão de domínio (fluency illusion) e melhora a capacidade de discriminar entre condições semelhantes na prova.",
    ctaLabel: "Ver distribuição no Plano",
    ctaTarget: "crono",
  },
  {
    id: "simulado",
    titulo: "Como Fazer um Simulado",
    l1: "Simulado sem correção sistemática dos erros é tempo perdido — o valor está no pós-simulado, não na nota.",
    l2: [
      "Cronometre: simule as condições reais da prova.",
      "Misture áreas: não faça blocos monográficos.",
      "Não persiga só o número: classifique cada erro.",
      "Revise o racional das erradas no mesmo dia.",
      "Refaça as erradas em 48–72h para fechar o loop.",
      "Use provas antigas da sua banca para calibrar o formato real.",
    ],
    l3: "Prática deliberada com feedback imediato (pós-simulado) é o que converte treino em melhora real. Simulados sem correção têm efeito próximo de zero no desempenho a longo prazo.",
    ctaLabel: "Registrar simulado",
    ctaTarget: "sims",
  },
  {
    id: "atraso",
    titulo: "Lidando com Atraso",
    l1: "Atraso acumulado não se resolve com maratona — se resolve com priorização cirúrgica dos itens mais críticos.",
    l2: [
      "Abra o Plano e veja quais temas estão mais atrasados.",
      "Priorize revisões vencidas de alta incidência ENAMED antes de temas novos.",
      "Reduza temporariamente o limite diário para um número que consiga cumprir.",
      "Um tema zerado e consolidado vale mais que três temas pela metade.",
      "Avise o Mentor sobre o contexto (carga alta, baixa energia) para calibrar.",
    ],
    l3: "Binge learning (maraton de conteúdo sem espaçamento) produz ilusão de domínio. Menos temas, mais consolidados, superam mais temas mal fixados no desempenho em prova.",
    ctaLabel: "Ver plano de hoje",
    ctaTarget: "crono",
  },
  {
    id: "corrigir_questao",
    titulo: "Como Corrigir uma Questão",
    l1: "Corrigir questão não é ler o gabarito — é entender POR QUE errou e QUE FATO resolve o erro definitivamente.",
    l2: [
      "Identifique o tipo de erro: lacuna de conteúdo, raciocínio, descuido, tempo ou interpretação.",
      "Se foi lacuna de conteúdo: crie um flashcard atômico com o fato específico que te fez errar.",
      "Se foi raciocínio: resolva um caso clínico ou illness script sobre o tema.",
      "Se foi descuido: anote o padrão e monitore recorrência.",
      "Não marque como 'fácil' apenas por ter acertado com chute.",
    ],
    l3: "A análise qualitativa do erro (por tipo e causa) reduz a reincidência em 40–60% comparado a apenas reler o gabarito.",
    ctaLabel: "Ver auditoria de erros",
    ctaTarget: "sims",
  },
  {
    id: "raciocinio_clinico",
    titulo: "Illness Script",
    l1: "Organizar um tema em illness script (predisponentes, mecanismo, consequências, conduta) treina o raciocínio clínico de forma estruturada.",
    l2: [
      "Para cada tema novo: quem adoece? (predisponentes/fatores de risco).",
      "O que acontece no organismo? (mecanismo fisiopatológico simplificado).",
      "Quais são os achados diagnósticos-chave? (exame físico + exames).",
      "Qual a conduta-padrão e os red flags?",
      "Crie um caso variante para treinar discriminação com diagnósticos semelhantes.",
    ],
    l3: "Illness scripts organizam informação dispersa em um esquema de decisão clínica. Experts pensam por illness scripts, não por listas. Treiná-los melhora o raciocínio em casos complexos.",
    ctaLabel: "Abrir Raciocínio Clínico",
    ctaTarget: "raciocinio",
  },
  {
    id: "d0",
    titulo: "Como Fazer o D0",
    l1: "O D0 é o estudo inicial do tema — a qualidade do D0 determina quanto você retém nas revisões seguintes.",
    l2: [
      "Pré-teste: 3–5 questões antes de abrir o material.",
      "Leitura ativa em bloco com pergunta-missão.",
      "Brain dump: 3 minutos sem material, escreva tudo que reteve.",
      "Questões pós-leitura: 10–15 questões com análise de erro.",
      "Crie flashcards dos fatos que errou ou que são atomicamente críticos.",
      "Anote o pico (vinheta clínica típica) do tema no card do cronograma.",
    ],
    l3: "Um D0 completo (pré-teste + leitura ativa + retrieval + questões) reduz o número de revisões necessárias e aumenta a estabilidade FSRS desde o primeiro ciclo.",
    ctaLabel: "Abrir Plano",
    ctaTarget: "crono",
  },
];
