// src/constants/provaStats.js
// REGRA: todo dado tem fonte+ano. null = não divulgado. Não inventar.

export const PROVA_STATS_RES = {
  "ENAMED": {
    banca: "INEP (aplicação) / FGV-ENARE (classificação acesso direto)",
    bancaHistorico: "Exame nacional unificado criado em 2025 (Portarias MEC/INEP 330, 359, 413/2025). Substitui a etapa teórica do ENARE para acesso direto e a antiga prova de concluintes.",
    ano: "2026 (2ª edição; prova em out)",
    fonte: "INEP/MEC (Port. 330/359/413/2025), ENARE/FGV, Agência Brasil, Estratégia MED/Medway - out/2025-mai/2026",
    perfil: { fase: "Fase única objetiva: 100 questões (4 alternativas, 1 correta), distribuição equitativa entre as 5 grandes áreas (~20 cada). Foco em SUS e DCNs.", questoes: 100,
      areas: ["Clínica Médica","Cirurgia Geral","GO","Pediatria","Preventiva"],
      vagasTotais: null, concorrenciaGeral: "Nota usada pelo ENARE (acesso direto), validade 3 anos. >96 mil inscritos em 2025; >7 mil vagas ENARE." },
    estilo: "Competências por DCNs, ênfase em SUS/APS/MFC; Saúde Coletiva e Saúde Mental transversais. Pesos iguais entre as 5 áreas; classificação no ENARE pela nota bruta.",
    mudancas: "2025: 1ª edição (19/out). 2026: integrada ao ENADE; nota válida por até 3 anos para ENARE acesso direto.",
    notasCorte: {
      "Clínica Médica": null, "Cirurgia Geral": null, "GO": null, "Pediatria": null, "Preventiva": null,
      "_obs": { valor: null, escala: 100, ano: "2026", obs: "ENAMED não tem corte único nacional; o corte varia por programa/instituição no ENARE." },
    },
    concorrencia: { "Dermatologia":"altíssima","Oftalmologia":"altíssima","Otorrinolaringologia":"alta",
      "Clínica Médica":"média","Cirurgia Geral":"média-alta","GO":"média","Pediatria":"média","Preventiva/MFC":"baixa-média" },
    temasQuentes: {
      "Clínica Médica": ["Cardiologia (IAM, IC, HAS)","Emergências hiperglicêmicas (CAD/EHH)","Infecto/SUS","Distúrbios ácido-base e hidroeletrolíticos"],
      "Cirurgia Geral": ["Abdome agudo","Trauma (ATLS)","Hérnias"],
      "GO": ["Pré-natal e sangramentos","Síndromes hipertensivas","Saúde da mulher na APS"],
      "Pediatria": ["Aleitamento","Imunização","Diarreia/desidratação","Puericultura"],
      "Preventiva": ["APS/ESF","SUS (princípios e legislação)","Níveis de prevenção","Indicadores de saúde","Saúde mental na APS","Vigilância/quimioprofilaxia"],
    },
  },

  "SES-DF": {
    banca: "IADES",
    bancaHistorico: "Migrou para IADES no ciclo 2026 (antes Quadrix/FUNATEC). Troca de banca muda o estilo.",
    ano: "2026 (ingresso)",
    fonte: "Estratégia MED / Medway / IADES (editais e resultados), out/2025–fev/2026",
    perfil: { fase: "Fase única: objetiva (80q acesso direto) + análise curricular.", questoes: 80,
      areas: ["Clínica Médica","Cirurgia Geral","GO","Pediatria","Preventiva"],
      vagasTotais: 574, concorrenciaGeral: "≈11,4 cand/vaga (6570/574, 2026)" },
    estilo: "Peso forte de Preventiva/SUS (contexto DF) e MFC. Objetiva, cobra conduta/diretrizes MS. Currículo entra na nota.",
    mudancas: "2026: banca IADES; escolha de cenário via SISRESID; currículo com 13 requisitos pontuados.",
    notasCorte: {
      "Clínica Médica": { valor: 90.9, escala: 100, ano: "2025", obs: "HBDF 1ª chamada AC (varia por hospital; HRAN ~86,9)" },
      "Cirurgia Geral": { valor: 85.7, escala: 100, ano: "2025", obs: "Residência Integrada COREME/SES-DF, 1ª chamada AC" },
      "GO": null, "Pediatria": null, "Neurologia": null, "Dermatologia": null,
      "Oftalmologia": null, "Otorrinolaringologia": null, "Psiquiatria": null,
    },
    concorrencia: { "Dermatologia":"altíssima","Otorrinolaringologia":"altíssima","Oftalmologia":"alta",
      "Neurocirurgia":"alta","Clínica Médica":"média","Cirurgia Geral":"média-alta","GO":"média",
      "Pediatria":"média","Preventiva/MFC":"baixa-média" },
    temasQuentes: {
      "Cirurgia Geral": ["Trauma (ATLS, abdominal, tórax)","Abdome agudo","Hérnias"],
      "Clínica Médica": ["Emergências hiperglicêmicas (CAD/EHH)","Cardiologia (IAM, IC)","Infecto/SUS"],
      "Preventiva": ["Níveis de prevenção","Indicadores de saúde","APS/ESF","SUS (legislação)"],
      "GO": ["Pré-natal","Síndromes hipertensivas","Sangramentos"],
      "Pediatria": ["Aleitamento","Imunização","Diarreia/desidratação"],
    },
  },

  "SUS-SP": {
    banca: "Fundação VUNESP",
    bancaHistorico: "VUNESP assumiu em 2025/2026 (novidade). Mudança de banca = mudança de estilo.",
    ano: "2026 (ingresso)",
    fonte: "Estratégia MED / Medway / MedCof / VUNESP (editais e resultados), out/2025–fev/2026; Aristo (temas).",
    perfil: { fase: "Fase única objetiva. Acesso direto = 100q (4h), 5 grandes áreas iguais (20 cada).", questoes: 100,
      areas: ["Clínica Médica","Cirurgia Geral","GO","Pediatria","Preventiva"],
      vagasTotais: 1431, concorrenciaGeral: "Maior prova de residência do país por volume." },
    estilo: "Ampla e equilibrada entre as 5 áreas; nota mínima 50% p/ habilitação. Bônus 10% cotas PPI. Desempate: CM > Cir > Ped > GO > Prev.",
    mudancas: "2025/26: banca VUNESP; hospitais do SMS-SP saíram (foram p/ ENARE/Enamed). VUNESP tende a ser direta, menos pegadinha.",
    notasCorte: {
      "_habilitacao": { valor: 50, escala: 100, ano: "2025", obs: "Mínimo p/ habilitação (não é corte por especialidade)" },
      "Clínica Médica": null, "Cirurgia Geral": null, "GO": null, "Pediatria": null,
      "Neurologia": null, "Dermatologia": null, "Oftalmologia": null, "Otorrinolaringologia": null, "Psiquiatria": null,
    },
    concorrencia: { "Dermatologia":"altíssima","Oftalmologia":"altíssima","Otorrinolaringologia":"alta",
      "Neurologia":"alta","Psiquiatria":"alta","Clínica Médica":"média","Cirurgia Geral":"média-alta","GO":"média","Pediatria":"média" },
    temasQuentes: {
      "Cirurgia Geral": ["Trauma abdominal + ATLS (forte histórico)","Abdome agudo","Resposta metabólica ao trauma"],
      "Clínica Médica": ["Cardiologia","Pneumologia (PAC, DPOC)","Endócrino (DM, tireoide)"],
      "GO": ["Obstetrícia (pré-natal, parto)","Sangramentos","Infecções"],
      "Pediatria": ["Neonatologia","Imunização","IVAS/pneumonia"],
      "Preventiva": ["SUS e legislação","Epidemiologia","APS"],
    },
  },

  "HC-FMUSP": {
    banca: "FUVEST (FMUSP)",
    ano: "2025 (ingresso) — última edição com notas por especialidade verificáveis",
    fonte: "PDF oficial HC-FMUSP/HCRP-USP (notas de corte R1 2024/2025, escala 0–10); Medway/Estratégia (perfil).",
    perfil: { fase: "1ª fase objetiva (peso 9) + 2ª fase análise/arguição curricular (~10%).", questoes: 120,
      areas: ["Cirurgia Geral","Clínica Médica","GO","Pediatria","Preventiva/MFC","Saúde Coletiva","Saúde Mental","Medicina de Urgência"],
      vagasTotais: 834, concorrenciaGeral: "≈13,3 cand/vaga (11082/834, 2025/26)" },
    estilo: "Uma das mais difíceis e conceituais do país. Fisiopatologia, raciocínio fino, detalhes acadêmicos. 120q em 6h.",
    mudancas: "Inclui Saúde Mental e Medicina de Urgência no acesso direto. FUVEST parou de divulgar nota final aberta; cortes abaixo são do PDF institucional HC R1 2024/2025.",
    notasCorte: {
      "Clínica Médica": { valor: 7.3, escala: 10, ano: "2024/2025", obs: "HC-FMUSP R1 acesso direto" },
      "Cirurgia Geral": { valor: 7.5, escala: 10, ano: "2024/2025" },
      "GO": { valor: 7.4, escala: 10, ano: "2024/2025", obs: "Obstetrícia e Ginecologia" },
      "Pediatria": { valor: 6.5, escala: 10, ano: "2024/2025" },
      "Neurologia": { valor: 7.5, escala: 10, ano: "2024/2025" },
      "Dermatologia": { valor: 7.8, escala: 10, ano: "2024/2025", obs: "uma das mais altas" },
      "Oftalmologia": { valor: 7.4, escala: 10, ano: "2024/2025" },
      "Otorrinolaringologia": { valor: 7.5, escala: 10, ano: "2024/2025" },
      "Psiquiatria": { valor: 7.3, escala: 10, ano: "2024/2025" },
      "Anestesiologia": { valor: 7.3, escala: 10, ano: "2024/2025" },
      "Ortopedia e Traumatologia": { valor: 6.4, escala: 10, ano: "2024/2025" },
      "Medicina de Emergência": { valor: 5.4, escala: 10, ano: "2024/2025" },
      "Medicina Intensiva": { valor: 6.0, escala: 10, ano: "2024/2025" },
      "Neurocirurgia": { valor: 7.8, escala: 10, ano: "2024/2025" },
      "Radiologia": { valor: 7.0, escala: 10, ano: "2024/2025" },
      "Medicina de Família e Comunidade": { valor: 5.0, escala: 10, ano: "2024/2025" },
      "Infectologia": { valor: 5.0, escala: 10, ano: "2024/2025" },
    },
    concorrencia: { "Dermatologia":"altíssima","Neurocirurgia":"altíssima","Cirurgia Geral":"alta",
      "Otorrinolaringologia":"alta","Neurologia":"alta","Clínica Médica":"alta","Psiquiatria":"alta",
      "Oftalmologia":"alta","GO":"alta","Pediatria":"média","Ortopedia e Traumatologia":"média",
      "Medicina de Família e Comunidade":"baixa","Infectologia":"baixa" },
    temasQuentes: {
      "Clínica Médica": ["Nefro (distúrbios hidroeletrolíticos, IRA)","Cardio","Reumato (perfil acadêmico USP)"],
      "Cirurgia Geral": ["Trauma","Abdome agudo","Cirurgia do aparelho digestivo"],
      "Preventiva": ["Epidemiologia avançada","MBE/estatística","SUS"],
      "GO": ["Obstetrícia de alto risco","Oncoginecologia"],
      "Pediatria": ["Neonatologia","Genética/erros inatos","Cardiopatias congênitas"],
    },
  },
};

export const PROVA_STATS_VEST = {
  "UnB": {
    banca: "Cebraspe", ano: "2024/2025",
    fonte: "Cebraspe (editais/resultados); passeandounb, reporteranadia, descomplica, 2024–2026.",
    perfil: { tipo: "Vestibular tradicional próprio (25% das vagas; PAS 50%; Acesso Enem/SiSU 25%).",
      etapas: "Objetiva + redação. Estilo Cebraspe.",
      areas: ["Linguagens","Humanas","Ciências da Natureza","Matemática","Redação"],
      vagasMedicina: "≈ metade das vagas de Medicina via vestibular tradicional" },
    estilo: "Cebraspe: prova densa, interpretação pesada, discursivas/redação rigorosas. Medicina é o curso mais concorrido.",
    mudancas: "Convive com PAS (seriado, 50%) e Acesso Enem próprio (Cebraspe, com nota Enem).",
    notaCorteMedicina: { argumento: { valor: 819.7, escala: 1000, ano: "2024", obs: "Argumento Medicina AC (≈819,5 em 2023)" } },
    temasQuentes: {
      "Ciências da Natureza": ["Genética","Fisiologia humana","Termoquímica","Eletromagnetismo"],
      "Matemática": ["Geometria","Funções","Probabilidade/estatística"],
      "Humanas": ["Brasil República","Geopolítica","Filosofia/Sociologia (contratualistas)"],
      "Linguagens": ["Interpretação","Literatura (obras do edital)","Norma culta"],
      "Redação": ["Dissertativo-argumentativo","Temas sociais contemporâneos"],
    },
  },

  "UFG": {
    banca: "Instituto Verbena (UFG)",
    ano: "2026 (1ª edição do vestibular próprio retomado após 11 anos)",
    fonte: "UFG (ufg.br) / Instituto Verbena (edital) / Estratégia Vestibulares / Colégio WR, jul–dez/2025.",
    perfil: { tipo: "Vestibular próprio (50% das vagas; SiSU/Enem nos outros 50%). Independente do Enem.",
      etapas: "Etapa única: 96 questões (24/área) + redação dissertativo-argumentativa.",
      areas: ["Linguagens","Humanas","Ciências da Natureza","Matemática","Redação"],
      vagasMedicina: "55 vagas via vestibular (de 110; 27 ampla concorrência)" },
    estilo: "Segue diretrizes do SiSU/Enem (reitoria: 'qualifica o SiSU'). Redação eliminatória (0 elimina; mín. 10/24). Estilo Enem-like.",
    mudancas: "PRIMEIRA edição — sem histórico de corte por curso. Usar corte do SiSU UFG Medicina como proxy rotulado.",
    notaCorteMedicina: { argumento: null, obs: "Sem série histórica. Proxy: nota de corte SiSU UFG Medicina." },
    temasQuentes: {
      "_obs": "Estilo Enem-like; priorizar competências do Enem. Histórico regional (Goiás) em Humanas/Geografia.",
      "Humanas": ["História/Geografia de Goiás e Brasil","Atualidades"],
      "Ciências da Natureza": ["Ecologia","Genética","Estequiometria","Mecânica"],
      "Matemática": ["Funções","Estatística","Geometria"],
      "Redação": ["Dissertativo-argumentativo (modelo Enem)"],
    },
  },
};

export const PROVAS_RES = ["ENAMED", "SES-DF", "SUS-SP", "HC-FMUSP"];
export const PROVAS_VEST = ["UnB", "UFG"];
