export const MEDREV_SAMPLE_CALENDAR = [
  {
    semana: "Semana 1",
    dia: "Segunda",
    data: null,
    area: "Clínica Médica",
    tema: "Dor torácica na emergência",
    ordem: 1,
    duracaoMin: 75,
    prioridade: "ALTA",
    observacoes: "Tema genérico MedRev para testar o fluxo.",
  },
  {
    semana: "Semana 1",
    dia: "Quarta",
    data: null,
    area: "Cirurgia",
    tema: "Abdome agudo: abordagem inicial",
    ordem: 2,
    duracaoMin: 75,
    prioridade: "ALTA",
    observacoes: "Sem conteúdo proprietário.",
  },
  {
    semana: "Semana 2",
    dia: "Segunda",
    data: null,
    area: "Pediatria",
    tema: "Febre em lactentes",
    ordem: 1,
    duracaoMin: 75,
    prioridade: "MEDIA",
    observacoes: "Amostra curta para onboarding.",
  },
  {
    semana: "Semana 2",
    dia: "Quinta",
    data: null,
    area: "Preventiva",
    tema: "Rastreamento e prevenção primária",
    ordem: 2,
    duracaoMin: 60,
    prioridade: "MEDIA",
    observacoes: "Amostra curta para onboarding.",
  },
  {
    semana: "Semana 3",
    dia: "Terça",
    data: null,
    area: "GO",
    tema: "Sangramento na gestação",
    ordem: 1,
    duracaoMin: 75,
    prioridade: "ALTA",
    observacoes: "Tema genérico MedRev para testar o fluxo.",
  },
  {
    semana: "Semana 3",
    dia: "Quinta",
    data: null,
    area: "Clínica Médica",
    tema: "Dispneia: diagnóstico diferencial",
    ordem: 2,
    duracaoMin: 75,
    prioridade: "ALTA",
    observacoes: "Tema genérico MedRev para testar o fluxo.",
  },
];
