import fs from "node:fs";

const temasNaoClinicos = [
  { temaId: "indicadores-de-saude", nome: "Indicadores de Saúde", motivo: "Tema conceitual/epidemiológico sem entidade clínica diagnosticável única." },
  { temaId: "anatomia-pelvica-feminina", nome: "Anatomia Pélvica Feminina", motivo: "Tema anatômico de base, melhor convertido em cards conceituais do que caso clínico." },
  { temaId: "testes-diagnosticos", nome: "Testes Diagnósticos", motivo: "Tema metodológico sem doença/condição clínica atômica." },
  { temaId: "determinacao-social-do-processo-saude-doenca", nome: "Determinação Social do Processo Saúde-Doença", motivo: "Tema conceitual de saúde coletiva." },
  { temaId: "redes-de-atencao-a-saude", nome: "Redes de Atenção à Saúde", motivo: "Tema administrativo/organizacional." },
  { temaId: "atencao-primaria-a-saude", nome: "Atenção Primária à Saúde", motivo: "Tema de organização do cuidado, não diagnóstico clínico atômico." },
  { temaId: "classificacao-dos-estudos-epidemiologicos", nome: "Classificação dos Estudos Epidemiológicos", motivo: "Tema metodológico." },
];

const data = [
  {
    cid: "anemias-hipoproliferativas-i__anemia-ferropriva",
    entidade: "Anemia ferropriva",
    temaId: "anemias-hipoproliferativas-i",
    temaNome: "Anemias Hipoproliferativas I",
    area: "Clínica Médica",
    sindrome: "Síndrome anêmica microcítica",
    enabling: ["menstruação volumosa", "baixa ingestão de ferro", "perda crônica de sangue"],
    fault: "Deficiência de ferro reduz síntese de hemoglobina e produz anemia microcítica hipocrômica.",
    consequences: ["fadiga", "palidez", "pica", "unhas frágeis"],
    management: ["confirmar ferritina baixa", "repor ferro oral quando possível", "investigar fonte de perda"],
    redFlags: ["sangramento digestivo", "instabilidade hemodinâmica", "perda ponderal"],
    keyFeatures: ["Diferenciar deficiência de ferro de talassemia/ doença crônica", "Pesquisar causa de perda crônica"],
    negatives: ["sem icterícia ou reticulocitose importante"],
    discriminators: [{ vs: "Talassemia menor", feature: "ferritina baixa e RDW elevado favorecem deficiência de ferro" }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "tratar com ferro sem buscar sangramento crônico em adulto" }],
    typical: {
      vignette: "Mulher de 32 anos relata fadiga progressiva, queda de cabelo e desejo de mastigar gelo. Refere fluxos menstruais intensos há um ano. Hemograma mostra Hb 9,6 g/dL, VCM 68 fL e RDW elevado.",
      representation: "mulher jovem com fadiga crônica, perdas menstruais intensas e anemia microcítica",
      options: ["Síndrome anêmica microcítica", "Síndrome hemolítica", "Pancitopenia medular"],
      justification: "Microcitose com história de perda crônica orienta deficiência de ferro.",
      differentials: ["talassemia menor", "anemia da doença crônica", "sideroblástica"],
    },
    atypical: {
      vignette: "Homem de 68 anos procura atendimento por dispneia aos esforços e tontura. Nega melena, mas relata uso frequente de anti-inflamatório. Hb 8,8 g/dL, VCM 70 fL e ferritina muito baixa.",
      representation: "idoso com sintomas anêmicos e microcitose por provável perda oculta",
      options: ["Síndrome anêmica microcítica", "Síndrome dispéptica funcional", "Síndrome consumptiva isolada"],
      justification: "Microcitose e ferritina baixa exigem investigação de perda gastrointestinal.",
      differentials: ["câncer colorretal", "úlcera péptica", "anemia da inflamação"],
    },
  },
  {
    cid: "assistencia-ao-pre-natal__pre-natal-baixo-risco",
    entidade: "Gestação de baixo risco em início de pré-natal",
    temaId: "assistencia-ao-pre-natal",
    temaNome: "Assistência ao Pré-Natal",
    area: "GO",
    sindrome: "Síndrome de gestação inicial sem sinais de alto risco",
    enabling: ["atraso menstrual", "teste positivo", "ausência de comorbidades graves"],
    fault: "A gestação inicial exige estratificação de risco, datação e rastreios para reduzir morbimortalidade materno-fetal.",
    consequences: ["necessidade de exames iniciais", "vacinação", "orientações e seguimento longitudinal"],
    management: ["confirmar idade gestacional", "solicitar rotina inicial", "estratificar risco", "programar consultas"],
    redFlags: ["sangramento importante", "dor pélvica intensa", "hipertensão", "diabetes prévio"],
    keyFeatures: ["Reconhecer baixo risco", "Iniciar rastreios e suplementação no tempo correto"],
    negatives: ["sem dor pélvica intensa ou sangramento volumoso"],
    discriminators: [{ vs: "Gestação ectópica", feature: "ausência de dor unilateral intensa e instabilidade reduz urgência imediata, mas não dispensa ultrassom quando indicado" }],
    errors: [{ tipo: "disponibilidade", armadilha: "focar só no ultrassom e esquecer sorologias, tipagem e estratificação de risco" }],
    typical: {
      vignette: "Mulher de 24 anos, G1P0, vem à UBS com atraso menstrual de 7 semanas e teste positivo. Está assintomática, PA 108/68, sem doenças conhecidas e sem sangramento.",
      representation: "gestante no primeiro trimestre, assintomática, sem critérios de alto risco",
      options: ["Síndrome de gestação inicial sem sinais de alto risco", "Abdome agudo ginecológico", "Síndrome hipertensiva gestacional"],
      justification: "Teste positivo e estabilidade clínica orientam início organizado do acompanhamento.",
      differentials: ["gestação ectópica", "abortamento inicial", "gestação de alto risco"],
    },
    atypical: {
      vignette: "Adolescente de 16 anos busca primeira consulta com atraso menstrual de 10 semanas. Nega dor ou sangramento, mora longe da unidade e não usa medicações.",
      representation: "gestante adolescente estável com vulnerabilidade social e necessidade de captação precoce",
      options: ["Síndrome de gestação inicial sem sinais de alto risco", "Síndrome de abortamento", "Doença hipertensiva específica da gestação"],
      justification: "Não há sinais de urgência, mas há necessidade de vínculo, rastreio e avaliação social.",
      differentials: ["gestação ectópica", "violência sexual", "gestação com vulnerabilidade"],
    },
  },
  {
    cid: "aleitamento-materno__mastite-puerperal",
    entidade: "Mastite puerperal",
    temaId: "aleitamento-materno",
    temaNome: "Aleitamento Materno",
    area: "Pediatria",
    sindrome: "Síndrome mamária puerperal febril",
    enabling: ["fissura mamilar", "estase láctea", "pega inadequada"],
    fault: "Estase e trauma mamilar favorecem inflamação e infecção bacteriana da mama no puerpério.",
    consequences: ["dor local", "eritema", "febre", "risco de abscesso"],
    management: ["manter esvaziamento da mama", "corrigir pega", "analgesia", "antibiótico se quadro infeccioso"],
    redFlags: ["flutuação local", "toxemia", "não melhora em 48 horas"],
    keyFeatures: ["Diferenciar ingurgitamento de infecção", "Evitar suspensão desnecessária do aleitamento"],
    negatives: ["sem massa flutuante no exame inicial"],
    discriminators: [{ vs: "Abscesso mamário", feature: "flutuação e persistência apesar de antibiótico sugerem coleção" }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "mandar suspender amamentação sem indicação" }],
    typical: {
      vignette: "Puérpera no 18º dia pós-parto apresenta dor em mama esquerda, febre e área triangular eritematosa. O bebê tem pega rasa e há fissura no mamilo.",
      representation: "puérpera lactante com febre, dor focal e eritema mamário",
      options: ["Síndrome mamária puerperal febril", "Síndrome gripal", "Dermatite de contato"],
      justification: "Dor focal, febre e eritema em lactante definem síndrome mamária infecciosa.",
      differentials: ["ingurgitamento mamário", "abscesso mamário", "candidíase mamilar"],
    },
    atypical: {
      vignette: "Mulher amamentando há 6 semanas relata calafrios e dor profunda em uma mama, com pouca alteração cutânea inicial. O lactente passou a mamar por intervalos longos à noite.",
      representation: "lactante com sintomas sistêmicos e dor mamária após estase láctea",
      options: ["Síndrome mamária puerperal febril", "Síndrome ansiosa puerperal", "Dor torácica pleurítica"],
      justification: "Estase seguida de febre/calafrios aponta para inflamação/infeção mamária.",
      differentials: ["ingurgitamento", "abscesso inicial", "dor musculoesquelética"],
    },
  },
  {
    cid: "introducao-ao-trauma-e-atendimento-inicial__choque-hemorragico-trauma",
    entidade: "Choque hemorrágico no trauma",
    temaId: "introducao-ao-trauma-e-atendimento-inicial",
    temaNome: "Introdução ao Trauma e Atendimento Inicial",
    area: "Cirurgia",
    sindrome: "Síndrome de choque no politrauma",
    enabling: ["trauma de alta energia", "hemorragia externa ou interna", "fratura pélvica"],
    fault: "Perda sanguínea aguda reduz pré-carga e perfusão tecidual, causando choque obstrutivo/hipovolêmico até prova em contrário no trauma.",
    consequences: ["taquicardia", "hipotensão tardia", "pele fria", "rebaixamento"],
    management: ["ABCDE", "controle de hemorragia", "protocolo de transfusão maciça", "cirurgia/embolização conforme foco"],
    redFlags: ["hipotensão persistente", "FAST positivo", "sangramento compressível não controlado"],
    keyFeatures: ["Priorizar controle de hemorragia no C", "Não atrasar tratamento por exames desnecessários"],
    negatives: ["sem sinais predominantes de pneumotórax hipertensivo"],
    discriminators: [{ vs: "Choque neurogênico", feature: "taquicardia e pele fria favorecem hipovolemia hemorrágica" }],
    errors: [{ tipo: "ancoragem", armadilha: "atribuir rebaixamento ao álcool e perder choque oculto" }],
    typical: {
      vignette: "Homem de 29 anos vítima de colisão moto-carro chega pálido, sudoreico, confuso, FC 132 e PA 86/54. Há deformidade pélvica e escoriações abdominais.",
      representation: "politrauma de alta energia com hipoperfusão e provável perda sanguínea",
      options: ["Síndrome de choque no politrauma", "Síndrome neurológica focal aguda", "Síndrome coronariana aguda"],
      justification: "Instabilidade após trauma até prova em contrário é hemorragia e exige controle imediato.",
      differentials: ["choque obstrutivo", "choque neurogênico", "intoxicação"],
    },
    atypical: {
      vignette: "Idosa atropelada chega lúcida, PA 104/70, FC 118, pele fria e dor em quadril. Após 20 minutos evolui com sonolência e enchimento capilar lento.",
      representation: "trauma com sinais precoces de hipoperfusão apesar de pressão inicial aparentemente preservada",
      options: ["Síndrome de choque no politrauma", "Síncope vasovagal", "Crise ansiosa"],
      justification: "Taquicardia, pele fria e piora neurológica sugerem choque compensado.",
      differentials: ["fratura pélvica hemorrágica", "trauma craniano", "choque cardiogênico"],
    },
  },
  {
    cid: "neurovascular-i-ait-e-avci__ataque-isquemico-transitorio",
    entidade: "Ataque isquêmico transitório",
    temaId: "neurovascular-i-ait-e-avci",
    temaNome: "Neurovascular I: AIT e AVCi",
    area: "Clínica Médica",
    sindrome: "Síndrome neurológica focal transitória",
    enabling: ["fibrilação atrial", "aterosclerose carotídea", "hipertensão"],
    fault: "Isquemia cerebral focal reversível causa déficit neurológico súbito sem infarto estabelecido.",
    consequences: ["alto risco precoce de AVC", "déficit focal resolvido", "necessidade de investigação urgente"],
    management: ["avaliar imagem", "estratificar risco", "antiagregação/anticoagulação conforme causa", "investigar carótidas e cardioembolia"],
    redFlags: ["déficit persistente", "afasia", "amaurose fugaz recorrente"],
    keyFeatures: ["Não tranquilizar pela resolução", "Investigar etiologia vascular rapidamente"],
    negatives: ["sem crise convulsiva presenciada"],
    discriminators: [{ vs: "Enxaqueca com aura", feature: "déficit negativo súbito e fatores vasculares favorecem evento isquêmico" }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "dispensar paciente porque os sintomas passaram" }],
    typical: {
      vignette: "Homem de 71 anos teve fraqueza súbita em braço direito e fala enrolada por 20 minutos, resolvidas antes da chegada. Tem hipertensão e tabagismo.",
      representation: "idoso com déficit focal súbito e transitório em território vascular",
      options: ["Síndrome neurológica focal transitória", "Síndrome vestibular periférica", "Crise funcional"],
      justification: "Déficit focal negativo, súbito e reversível define evento vascular transitório até prova contrária.",
      differentials: ["AVC isquêmico", "enxaqueca com aura", "crise epiléptica focal"],
    },
    atypical: {
      vignette: "Mulher de 66 anos relata perda visual monocular esquerda por 8 minutos, como uma cortina descendo, com recuperação completa. Ausculta cervical sugere sopro.",
      representation: "evento visual monocular transitório em paciente com risco aterosclerótico",
      options: ["Síndrome neurológica focal transitória", "Síndrome ocular alérgica", "Cefaleia primária"],
      justification: "Amaurose fugaz é manifestação vascular focal transitória.",
      differentials: ["oclusão de artéria retiniana", "neurite óptica", "descolamento de retina"],
    },
  },
  {
    cid: "neurovascular-i-ait-e-avci__avc-isquemico",
    entidade: "AVC isquêmico",
    temaId: "neurovascular-i-ait-e-avci",
    temaNome: "Neurovascular I: AIT e AVCi",
    area: "Clínica Médica",
    sindrome: "Síndrome neurológica focal aguda",
    enabling: ["hipertensão", "diabetes", "fibrilação atrial", "aterosclerose"],
    fault: "Oclusão arterial cerebral causa hipoperfusão focal e déficit neurológico súbito persistente.",
    consequences: ["hemiparesia", "afasia", "negligência", "risco de edema"],
    management: ["definir horário de início", "TC sem contraste", "glicemia", "avaliar trombólise/trombectomia"],
    redFlags: ["rebaixamento", "cefaleia explosiva", "janela terapêutica"],
    keyFeatures: ["Diferenciar de hemorragia com imagem", "Não perder janela de reperfusão"],
    negatives: ["sem hipoglicemia explicando déficit"],
    discriminators: [{ vs: "Paralisia de Todd", feature: "ausência de crise e déficit em território vascular favorecem isquemia" }],
    errors: [{ tipo: "disponibilidade", armadilha: "atribuir fala alterada a confusão metabólica sem exame neurológico focal" }],
    typical: {
      vignette: "Homem de 64 anos iniciou há 70 minutos desvio de rima, fraqueza em hemicorpo direito e dificuldade para nomear objetos. Glicemia capilar 112 mg/dL.",
      representation: "déficit neurológico focal súbito persistente em janela terapêutica",
      options: ["Síndrome neurológica focal aguda", "Síndrome confusional metabólica", "Síndrome vestibular periférica"],
      justification: "Instalação súbita, focalidade e persistência indicam evento cerebrovascular agudo.",
      differentials: ["hemorragia intracraniana", "hipoglicemia", "crise epiléptica"],
    },
    atypical: {
      vignette: "Mulher de 78 anos acorda com desatenção ao lado esquerdo, queda ao tentar levantar e olhar desviado. Família não sabe o horário exato em que ficou bem pela última vez.",
      representation: "déficit focal ao despertar com provável acometimento hemisférico direito",
      options: ["Síndrome neurológica focal aguda", "Delirium hipoativo", "Vertigem periférica"],
      justification: "Negligência e desvio ocular são sinais corticais de evento vascular.",
      differentials: ["AVC hemorrágico", "tumor com sangramento", "encefalopatia metabólica"],
    },
  },
  {
    cid: "nefrologia-pediatrica__sindrome-nefrotica",
    entidade: "Síndrome nefrótica idiopática",
    temaId: "nefrologia-pediatrica",
    temaNome: "Nefrologia Pediátrica",
    area: "Pediatria",
    sindrome: "Síndrome edematosa com proteinúria",
    enabling: ["idade pré-escolar", "doença de lesões mínimas", "infecção viral recente"],
    fault: "Aumento da permeabilidade glomerular leva a proteinúria maciça, hipoalbuminemia e edema.",
    consequences: ["edema periorbitário", "ascite", "risco trombótico", "infecções"],
    management: ["confirmar proteinúria", "avaliar albumina e função renal", "corticoterapia quando indicado", "orientar sinais de gravidade"],
    redFlags: ["hematúria importante", "hipertensão grave", "queda de função renal"],
    keyFeatures: ["Separar síndrome nefrótica de nefrítica", "Reconhecer sinais atípicos"],
    negatives: ["sem hipertensão ou hematúria exuberante"],
    discriminators: [{ vs: "Glomerulonefrite aguda", feature: "proteinúria maciça e edema sem hematúria importante favorecem síndrome nefrótica" }],
    errors: [{ tipo: "ancoragem", armadilha: "tratar edema como alergia por ser periorbitário" }],
    typical: {
      vignette: "Menino de 4 anos acorda há uma semana com olhos inchados e agora apresenta edema em pernas. Urina sem sangue visível. PA normal e fita urinária com proteína 4+.",
      representation: "pré-escolar com edema progressivo e proteinúria intensa sem sinais nefríticos dominantes",
      options: ["Síndrome edematosa com proteinúria", "Síndrome nefrítica hipertensiva", "Síndrome alérgica"],
      justification: "Edema com proteinúria intensa define síndrome nefrótica provável.",
      differentials: ["glomerulonefrite", "insuficiência cardíaca", "hepatopatia"],
    },
    atypical: {
      vignette: "Criança de 7 anos retorna por aumento abdominal e espuma na urina após quadro viral. Exame mostra edema discreto, albumina baixa e creatinina normal.",
      representation: "criança com hipoalbuminemia e perda urinária de proteína após infecção",
      options: ["Síndrome edematosa com proteinúria", "Ascite por hepatopatia", "Síndrome diarréica"],
      justification: "Proteinúria e albumina baixa explicam edema/ascite.",
      differentials: ["enteropatia perdedora de proteínas", "hepatopatia crônica", "glomerulonefrite"],
    },
  },
  {
    cid: "nefrologia-pediatrica__glomerulonefrite-pos-estreptococica",
    entidade: "Glomerulonefrite pós-estreptocócica",
    temaId: "nefrologia-pediatrica",
    temaNome: "Nefrologia Pediátrica",
    area: "Pediatria",
    sindrome: "Síndrome nefrítica aguda",
    enabling: ["faringite ou impetigo recente", "idade escolar", "baixo complemento"],
    fault: "Resposta imune pós-infecciosa causa inflamação glomerular com hematúria, retenção de sal e queda de filtração.",
    consequences: ["urina escura", "edema", "hipertensão", "oligúria"],
    management: ["controle pressórico e hídrico", "avaliar função renal/complemento", "tratar foco estreptocócico se presente"],
    redFlags: ["encefalopatia hipertensiva", "hipercalemia", "edema pulmonar"],
    keyFeatures: ["Reconhecer tríade nefrítica", "Monitorar complicações de hipertensão/oligúria"],
    negatives: ["sem proteinúria maciça isolada como manifestação principal"],
    discriminators: [{ vs: "Síndrome nefrótica", feature: "hematúria escura e hipertensão favorecem síndrome nefrítica" }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "atribuir urina escura a desidratação sem medir PA e urina tipo 1" }],
    typical: {
      vignette: "Menino de 8 anos apresenta edema palpebral, urina cor de coca-cola e cefaleia. Teve impetigo há três semanas. PA 138/92.",
      representation: "escolar com hematúria macroscópica, edema e hipertensão após infecção cutânea",
      options: ["Síndrome nefrítica aguda", "Síndrome edematosa com proteinúria", "Infecção urinária baixa"],
      justification: "Hematúria escura, edema e hipertensão configuram síndrome nefrítica.",
      differentials: ["nefropatia por IgA", "lúpus", "síndrome nefrótica"],
    },
    atypical: {
      vignette: "Criança de 6 anos chega por vômitos e sonolência. A mãe notou urina escura e redução do volume urinário. PA muito elevada para a idade.",
      representation: "criança com oligúria, hematúria e sinais neurológicos por hipertensão",
      options: ["Síndrome nefrítica aguda", "Meningoencefalite", "Gastroenterite com desidratação"],
      justification: "Urina escura, oligúria e hipertensão apontam para glomerulonefrite com gravidade.",
      differentials: ["síndrome hemolítico-urêmica", "glomerulonefrite rapidamente progressiva", "pielonefrite"],
    },
  },
  {
    cid: "trauma-de-torax__pneumotorax-hipertensivo",
    entidade: "Pneumotórax hipertensivo traumático",
    temaId: "trauma-de-torax",
    temaNome: "Trauma de Tórax",
    area: "Cirurgia",
    sindrome: "Síndrome de choque obstrutivo no trauma torácico",
    enabling: ["trauma penetrante", "ventilação com pressão positiva", "fratura costal"],
    fault: "Entrada de ar sob pressão no espaço pleural colapsa pulmão e reduz retorno venoso.",
    consequences: ["dispneia", "hipotensão", "turgência jugular", "murmúrio abolido"],
    management: ["descompressão imediata", "dreno torácico", "ABCDE"],
    redFlags: ["instabilidade hemodinâmica", "hipóxia refratária"],
    keyFeatures: ["Diagnóstico clínico em instável", "Descompressão antes de imagem"],
    negatives: ["sem macicez à percussão que sugira hemotórax maciço"],
    discriminators: [{ vs: "Hemotórax maciço", feature: "hipertimpanismo e murmúrio abolido favorecem pneumotórax" }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "aguardar radiografia em paciente instável" }],
    typical: {
      vignette: "Homem esfaqueado no hemitórax direito chega agitado, dispneico, PA 78/50, SatO2 84%, com murmúrio abolido e turgência jugular.",
      representation: "trauma torácico penetrante com hipóxia e choque obstrutivo",
      options: ["Síndrome de choque obstrutivo no trauma torácico", "Síndrome hemorrágica abdominal", "Síndrome coronariana aguda"],
      justification: "Instabilidade, hipoxemia e achados unilaterais torácicos indicam descompressão imediata.",
      differentials: ["hemotórax maciço", "tamponamento cardíaco", "contusão pulmonar"],
    },
    atypical: {
      vignette: "Paciente intubado após colisão evolui subitamente com queda de saturação, aumento de pressão no ventilador e hipotensão. Um lado do tórax expande menos.",
      representation: "trauma ventilado com deterioração respiratória e hemodinâmica abrupta",
      options: ["Síndrome de choque obstrutivo no trauma torácico", "Broncoaspiração isolada", "Edema agudo pulmonar"],
      justification: "Piora súbita em ventilação positiva após trauma sugere ar sob tensão.",
      differentials: ["intubação seletiva", "tamponamento", "embolia aérea"],
    },
  },
  {
    cid: "trauma-de-torax__hemotorax-macico",
    entidade: "Hemotórax maciço",
    temaId: "trauma-de-torax",
    temaNome: "Trauma de Tórax",
    area: "Cirurgia",
    sindrome: "Síndrome hemorrágica intratorácica traumática",
    enabling: ["trauma penetrante", "lesão vascular intercostal", "lesão pulmonar"],
    fault: "Acúmulo volumoso de sangue no espaço pleural compromete ventilação e causa choque hemorrágico.",
    consequences: ["dispneia", "macicez", "murmúrio reduzido", "choque"],
    management: ["dreno torácico calibroso", "reposição hemostática", "toracotomia se débito maciço/persistente"],
    redFlags: ["débito inicial muito alto", "sangramento contínuo", "instabilidade"],
    keyFeatures: ["Diferenciar de pneumotórax por percussão", "Reconhecer critérios de toracotomia"],
    negatives: ["sem hipertimpanismo predominante"],
    discriminators: [{ vs: "Pneumotórax hipertensivo", feature: "macicez à percussão favorece sangue no espaço pleural" }],
    errors: [{ tipo: "ancoragem", armadilha: "tratar só como pneumotórax e atrasar reposição/transfusão" }],
    typical: {
      vignette: "Homem baleado em hemitórax esquerdo chega pálido, FC 136, PA 82/48. Há macicez e murmúrio muito reduzido à esquerda.",
      representation: "trauma torácico penetrante com choque e derrame pleural traumático volumoso",
      options: ["Síndrome hemorrágica intratorácica traumática", "Síndrome de choque séptico", "Síndrome broncoespástica"],
      justification: "Macicez unilateral e choque após ferimento torácico sugerem grande volume de sangue pleural.",
      differentials: ["pneumotórax hipertensivo", "tamponamento", "lesão abdominal associada"],
    },
    atypical: {
      vignette: "Após queda de altura, idoso anticoagulado apresenta dispneia progressiva, dor torácica e hipotensão leve. Radiografia mostra opacificação de metade do hemitórax.",
      representation: "trauma fechado com coleção pleural volumosa e sinais de perda sanguínea",
      options: ["Síndrome hemorrágica intratorácica traumática", "Derrame pleural crônico", "Pneumonia extensa"],
      justification: "Contexto traumático e instabilidade tornam coleção pleural sanguínea provável.",
      differentials: ["contusão pulmonar", "derrame pleural prévio", "atelectasia"],
    },
  },
  {
    cid: "sifilis__sifilis-primaria",
    entidade: "Sífilis primária",
    temaId: "sifilis",
    temaNome: "Sífilis",
    area: "Clínica Médica",
    sindrome: "Síndrome de úlcera genital indolor",
    enabling: ["exposição sexual desprotegida", "múltiplas parcerias", "coinfecções"],
    fault: "Infecção por Treponema pallidum causa cancro duro no local de inoculação.",
    consequences: ["úlcera única", "adenopatia regional", "progressão para fases sistêmicas"],
    management: ["testes treponêmico/não treponêmico", "penicilina benzatina", "tratar parcerias", "rastrear ISTs"],
    redFlags: ["gestação", "sinais neurológicos", "coinfecção HIV"],
    keyFeatures: ["Reconhecer úlcera indolor", "Tratar e rastrear parcerias"],
    negatives: ["sem vesículas dolorosas agrupadas"],
    discriminators: [{ vs: "Herpes genital", feature: "lesão indolor única e base endurecida favorecem cancro duro" }],
    errors: [{ tipo: "disponibilidade", armadilha: "assumir que toda úlcera genital é herpes" }],
    typical: {
      vignette: "Homem de 27 anos nota ferida única em pênis há 10 dias. A lesão não dói, tem base endurecida e há linfonodos inguinais pequenos.",
      representation: "adulto jovem com úlcera genital única e indolor após exposição sexual",
      options: ["Síndrome de úlcera genital indolor", "Síndrome uretral purulenta", "Síndrome escrotal aguda"],
      justification: "Úlcera única, limpa e indolor sugere cancro duro.",
      differentials: ["herpes genital", "cancroide", "linfogranuloma venéreo"],
    },
    atypical: {
      vignette: "Mulher de 31 anos procura consulta por linfonodo inguinal e discreto desconforto vulvar. Ao exame, há pequena erosão firme em introito, pouco dolorosa.",
      representation: "mulher com lesão genital discreta e adenopatia regional",
      options: ["Síndrome de úlcera genital indolor", "Vulvovaginite irritativa", "Bartholinite"],
      justification: "Lesão firme e pouco dolorosa com adenopatia orienta IST ulcerativa treponêmica.",
      differentials: ["trauma local", "herpes", "cancroide"],
    },
  },
  {
    cid: "sifilis__sifilis-secundaria",
    entidade: "Sífilis secundária",
    temaId: "sifilis",
    temaNome: "Sífilis",
    area: "Clínica Médica",
    sindrome: "Síndrome exantemática palmoplantar com sintomas sistêmicos",
    enabling: ["sífilis primária não tratada", "exposição sexual", "HIV"],
    fault: "Disseminação hematogênica do treponema gera manifestações cutâneo-mucosas e sistêmicas.",
    consequences: ["rash palmoplantar", "placas mucosas", "condiloma plano", "linfonodomegalia"],
    management: ["confirmar sorologia", "penicilina benzatina", "rastrear HIV/hepatites", "notificar/tratar parcerias"],
    redFlags: ["gestação", "sintomas neurológicos/oculares"],
    keyFeatures: ["Pensar em sífilis no rash palmoplantar", "Rastrear coinfecções"],
    negatives: ["sem pródromo respiratório típico de virose exantemática infantil"],
    discriminators: [{ vs: "Exantema viral", feature: "acometimento de palmas/plantas e lesões mucosas favorecem sífilis" }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "tratar como alergia medicamentosa sem história sexual e sorologia" }],
    typical: {
      vignette: "Homem de 34 anos tem manchas difusas inclusive em palmas e plantas, febre baixa e placas esbranquiçadas em mucosa oral. Refere ferida genital que sumiu meses antes.",
      representation: "adulto com exantema palmoplantar e lesões mucosas após úlcera prévia",
      options: ["Síndrome exantemática palmoplantar com sintomas sistêmicos", "Urticária aguda", "Celulite bacteriana"],
      justification: "Rash palmoplantar e lesões mucosas são padrão de disseminação treponêmica.",
      differentials: ["exantema viral", "farmacodermia", "pitiríase rósea"],
    },
    atypical: {
      vignette: "Gestante no segundo trimestre apresenta alopecia em clareira, mal-estar e pápulas úmidas em região perianal. Não lembra de úlcera genital.",
      representation: "gestante com lesões mucocutâneas disseminadas e risco fetal",
      options: ["Síndrome exantemática palmoplantar com sintomas sistêmicos", "Dermatite seborreica isolada", "Candidíase cutânea"],
      justification: "Condiloma plano e alopecia em clareira sugerem fase sistêmica da infecção.",
      differentials: ["HPV", "psoríase", "micose superficial"],
    },
  },
];

const more = [
  ["corrimentos-vaginais__vaginose-bacteriana","Vaginose bacteriana","corrimentos-vaginais","Corrimentos Vaginais","GO","Síndrome de corrimento vaginal com odor","desequilíbrio da flora vaginal","Corrimento fino acinzentado com odor após relação, pouco prurido e pH elevado.","mulher com corrimento vaginal fétido e poucos sinais inflamatórios","Candidíase vulvovaginal","odor amínico e pouco prurido favorecem vaginose"],
  ["corrimentos-vaginais__candidiase-vulvovaginal","Candidíase vulvovaginal","corrimentos-vaginais","Corrimentos Vaginais","GO","Síndrome vulvovaginal pruriginosa","proliferação de Candida associada a alteração local","Mulher com prurido intenso, dispareunia e corrimento branco grumoso, sem odor forte.","mulher com vulvovaginite pruriginosa e corrimento grumoso","Vaginose bacteriana","prurido intenso e inflamação vulvar favorecem Candida"],
  ["alergia-alimentar-refluxo-e-constipacao__alergia-proteina-leite-vaca","Alergia à proteína do leite de vaca","alergia-alimentar-refluxo-e-constipacao","Alergia Alimentar, Refluxo e Constipação","Pediatria","Síndrome gastrointestinal/alérgica do lactente","reação imunológica a proteínas do leite","Lactente com sangue nas fezes, irritabilidade e eczema após fórmula, mantendo bom estado geral.","lactente com manifestações gastrocutâneas associadas ao leite","Intolerância à lactose","sangue nas fezes e eczema favorecem alergia alimentar"],
  ["alergia-alimentar-refluxo-e-constipacao__constipacao-funcional","Constipação funcional","alergia-alimentar-refluxo-e-constipacao","Alergia Alimentar, Refluxo e Constipação","Pediatria","Síndrome de constipação crônica sem alarme","retenção fecal comportamental e fezes endurecidas","Pré-escolar evacua a cada 5 dias, com fezes volumosas, escape fecal e dor ao evacuar desde desfralde.","criança com retenção fecal crônica e escape","Doença de Hirschsprung","início após desfralde e crescimento normal favorecem funcional"],
  ["trauma-abdominal__lesao-esplenica","Lesão esplênica traumática","trauma-abdominal","Trauma Abdominal","Cirurgia","Síndrome hemorrágica abdominal pós-trauma","laceração esplênica após trauma contuso","Jovem após colisão apresenta dor em hipocôndrio esquerdo, dor referida no ombro e queda progressiva de PA.","trauma contuso com dor em quadrante superior esquerdo e hipoperfusão","Lesão hepática","dor à esquerda e sinal referido ao ombro favorecem baço"],
  ["trauma-abdominal__peritonite-traumatica","Perfuração de víscera oca traumática","trauma-abdominal","Trauma Abdominal","Cirurgia","Síndrome peritoneal pós-trauma","ruptura de alça com extravasamento entérico","Homem com ferimento abdominal apresenta dor difusa, defesa involuntária e piora progressiva após período inicial estável.","trauma abdominal com irritação peritoneal progressiva","Contusão de parede","defesa involuntária e piora progressiva favorecem perfuração"],
  ["assistencia-ao-parto__distocia-de-ombro","Distocia de ombro","assistencia-ao-parto","Assistência ao Parto","GO","Emergência mecânica do parto vaginal","impactação do ombro anterior após saída da cabeça","Durante parto vaginal, a cabeça exterioriza e retrai contra o períneo, sem desprendimento dos ombros com tração habitual.","parto vaginal com cabeça exteriorizada e ombros impactados","Circular de cordão","sinal da tartaruga e falha de desprendimento favorecem distocia"],
  ["assistencia-ao-parto__trabalho-de-parto-ativo","Trabalho de parto ativo","assistencia-ao-parto","Assistência ao Parto","GO","Síndrome de parto em fase ativa","contrações efetivas com dilatação progressiva","Gestante a termo chega com contrações regulares, colo apagado, 6 cm de dilatação e bolsa íntegra.","gestante a termo com contrações regulares e dilatação avançada","Falso trabalho de parto","dilatação progressiva e contrações regulares favorecem fase ativa"],
  ["crescimento-e-baixa-estatura__baixa-estatura-familiar","Baixa estatura familiar","crescimento-e-baixa-estatura","Crescimento e Baixa Estatura","Pediatria","Síndrome de baixa estatura proporcional com velocidade normal","potencial genético baixo","Menino saudável está abaixo do percentil 3, mas cresce em velocidade normal; pais são baixos e idade óssea compatível.","criança proporcionalmente baixa com crescimento preservado","Deficiência de GH","velocidade normal e alvo familiar baixo favorecem variante familiar"],
  ["crescimento-e-baixa-estatura__deficiencia-hormonio-crescimento","Deficiência de hormônio do crescimento","crescimento-e-baixa-estatura","Crescimento e Baixa Estatura","Pediatria","Síndrome de baixa estatura com velocidade reduzida","produção insuficiente de GH","Criança cai percentis ao longo de 2 anos, tem adiposidade central discreta e idade óssea atrasada.","criança com desaceleração do crescimento e atraso de idade óssea","Baixa estatura familiar","queda de velocidade de crescimento favorece causa patológica"],
  ["trauma-cranioencefalico__hematoma-epidural","Hematoma epidural traumático","trauma-cranioencefalico","Trauma Cranioencefálico","Cirurgia","Síndrome de deterioração neurológica pós-trauma","sangramento arterial entre crânio e dura","Jovem bate a têmpora, melhora inicialmente e depois evolui com cefaleia intensa, vômitos e anisocoria.","TCE com intervalo lúcido e deterioração neurológica","Concussão simples","piora após intervalo lúcido e anisocoria favorecem hematoma expansivo"],
  ["trauma-cranioencefalico__hipertensao-intracraniana-traumatica","Hipertensão intracraniana traumática","trauma-cranioencefalico","Trauma Cranioencefálico","Cirurgia","Síndrome de hipertensão intracraniana aguda","edema/lesão expansiva elevando pressão intracraniana","Politraumatizado apresenta rebaixamento progressivo, vômitos, bradicardia e hipertensão após TCE fechado.","TCE com sinais sistêmicos de pressão intracraniana elevada","Choque hemorrágico isolado","bradicardia com hipertensão e rebaixamento favorecem hipertensão intracraniana"],
  ["dor-toracica-coronariana__iam-com-supra","Infarto agudo do miocárdio com supra de ST","dor-toracica-coronariana","Dor Torácica Coronariana","Clínica Médica","Síndrome coronariana aguda com supra","oclusão coronária aguda transmural","Homem de 58 anos tem dor opressiva há 50 minutos, sudorese e náuseas; ECG mostra elevação de ST em derivações inferiores.","adulto com dor torácica isquêmica persistente e supra de ST","Pericardite aguda","supra localizado com dor opressiva e sintomas autonômicos favorece IAM"],
  ["dor-toracica-coronariana__angina-instavel","Angina instável","dor-toracica-coronariana","Dor Torácica Coronariana","Clínica Médica","Síndrome coronariana aguda sem supra","instabilização de placa sem necrose detectável inicial","Mulher de 63 anos relata dor opressiva em repouso, recorrente, ECG sem supra e troponina inicial normal.","dor torácica isquêmica em repouso sem necrose inicial","Dor musculoesquelética","dor em repouso com fatores de risco favorece SCA sem supra"],
  ["amenorreia-primaria__sindrome-de-turner","Síndrome de Turner","amenorreia-primaria","Amenorreia Primária","GO","Síndrome de amenorreia primária com hipogonadismo hipergonadotrófico","disgenesia gonadal por monossomia/alteração do X","Adolescente de 15 anos nunca menstruou, tem baixa estatura, mamas pouco desenvolvidas e FSH elevado.","adolescente com amenorreia primária, baixa estatura e atraso puberal","Agenesia mülleriana","ausência de desenvolvimento mamário e FSH alto favorecem disgenesia gonadal"],
  ["amenorreia-primaria__agenesia-mulleriana","Agenesia mülleriana","amenorreia-primaria","Amenorreia Primária","GO","Síndrome de amenorreia primária com caracteres sexuais presentes","ausência congênita de útero e parte superior da vagina","Adolescente de 16 anos nunca menstruou, tem desenvolvimento mamário normal e dor cíclica ausente; ultrassom não identifica útero.","amenorreia primária com puberdade normal e ausência uterina","Síndrome de Turner","mamas desenvolvidas e ovários funcionantes favorecem agenesia mülleriana"],
  ["diarreia-aguda-em-pediatria__gastroenterite-aguda-com-desidratacao","Gastroenterite aguda com desidratação","diarreia-aguda-em-pediatria","Diarreia Aguda em Pediatria","Pediatria","Síndrome diarreica aguda com desidratação","perda hidroeletrolítica por infecção entérica","Lactente tem diarreia aquosa há 2 dias, vômitos, sede intensa, olhos fundos e tempo de enchimento capilar lentificado.","criança com diarreia aquosa aguda e sinais de desidratação","Disenteria bacteriana","ausência de sangue e predomínio aquoso favorecem gastroenterite viral"],
  ["diarreia-aguda-em-pediatria__disenteria-bacteriana","Disenteria bacteriana","diarreia-aguda-em-pediatria","Diarreia Aguda em Pediatria","Pediatria","Síndrome disentérica aguda","invasão/inflamação colônica por bactéria enteroinvasiva","Criança de 5 anos apresenta febre, dor abdominal e evacuações frequentes com muco e sangue há 24 horas.","criança febril com diarreia sanguinolenta e dor abdominal","Gastroenterite viral","sangue, muco e febre favorecem colite invasiva"],
];

const fallbackDiferenciaisPorArea = {
  "Clínica Médica": ["Pneumonia adquirida na comunidade", "Tromboembolismo pulmonar", "Síndrome coronariana aguda", "Sepse"],
  GO: ["Gestação ectópica tubária", "Doença inflamatória pélvica aguda", "Abortamento inicial", "Pré-eclâmpsia"],
  Pediatria: ["Pneumonia bacteriana típica", "Infecção urinária febril", "Sepse pediátrica", "Gastroenterite aguda"],
  Cirurgia: ["Apendicite aguda", "Obstrução intestinal", "Colecistite aguda", "Trauma abdominal"],
  Preventiva: ["Tuberculose pulmonar", "Dengue", "Episódio depressivo maior", "Transtorno de pânico"],
};

function differentialSeed(area, primary) {
  const seen = new Set();
  return [primary, ...(fallbackDiferenciaisPorArea[area] || fallbackDiferenciaisPorArea["Clínica Médica"])]
    .filter(Boolean)
    .filter((dx) => {
      const key = dx.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, 3);
}

for (const [cid, entidade, temaId, temaNome, area, sindrome, fault, vignette, representation, vs, feature] of more) {
  data.push({
    cid, entidade, temaId, temaNome, area, sindrome,
    enabling: ["fator de risco clínico compatível", "contexto epidemiológico provável"],
    fault,
    consequences: ["sintomas cardinais", "risco de complicação se não reconhecido"],
    management: ["confirmar diagnóstico sindrômico", "avaliar gravidade", "instituir conduta inicial adequada"],
    redFlags: ["instabilidade clínica", "sinais de gravidade", "falha de resposta inicial"],
    keyFeatures: ["Determinar a síndrome antes do diagnóstico", "Comparar confundíveis da mesma apresentação"],
    negatives: ["sem achado dominante que aponte para confundível principal"],
    discriminators: [{ vs, feature }],
    errors: [{ tipo: "fechamento_precoce", armadilha: "ancorar no primeiro diagnóstico sem comparar diferenciais da síndrome" }],
    typical: {
      vignette,
      representation,
      options: [sindrome, "Síndrome infecciosa inespecífica", "Síndrome funcional sem alarme"],
      justification: "Os achados centrais definem a síndrome e orientam os diferenciais mais próximos.",
      differentials: differentialSeed(area, vs),
    },
    atypical: {
      vignette: `${vignette} Em apresentação menos clássica, os achados são discretos e o principal erro é ignorar o padrão sindrômico.`,
      representation: `${representation} com sinais menos exuberantes`,
      options: [sindrome, "Síndrome inespecífica", "Quadro funcional isolado"],
      justification: "Mesmo com menor exuberância, o conjunto ainda pertence à mesma síndrome clínica.",
      differentials: differentialSeed(area, vs),
    },
  });
}

function buildCase(item) {
  return {
    script: {
      id: item.cid,
      entidade: item.entidade,
      area: item.area,
      subtopico: item.temaNome,
      sindrome: item.sindrome,
      incidenciaEnamed: "alta",
      enabling: item.enabling,
      fault: item.fault,
      consequences: item.consequences,
      management: item.management,
      redFlags: item.redFlags,
      keyFeatures: item.keyFeatures.slice(0, 3).map((prompt) => ({
        prompt,
        expectedAction: "Definir a síndrome, comparar diferenciais próximos e escolher a conduta inicial segura.",
        isCritical: true,
      })),
      pertinentNegatives: item.negatives,
      discriminators: item.discriminators,
      commonErrors: item.errors,
    },
    instances: [
      buildInstance(item, item.typical, "typical"),
      buildInstance(item, item.atypical, "atypical"),
    ],
  };
}

function buildInstance(item, source, presentation) {
  return {
    id: `${item.cid}-${presentation}`,
    scriptId: item.cid,
    presentation,
    vignette: source.vignette,
    determinacaoSindromica: {
      prompt: "Antes do diagnóstico específico, qual síndrome melhor representa este quadro?",
      problemRepresentation: source.representation,
      sindromeCorreta: item.sindrome,
      opcoes: source.options,
      justificativa: source.justification,
      diferenciaisDaSindrome: source.differentials,
    },
    differentials: source.differentials.map((dx, index) => ({
      dx,
      plausibilidade: index === 0 ? "alta" : "media",
      pista: index === 0 ? "principal confundível a comparar" : "considerar conforme evolução e exames",
    })),
    workupChave: item.management.slice(0, 3),
    diagnosticoFinal: item.entidade,
    justificativa: `${source.justification} A decisão final deve ser revisada por humano antes de publicação.`,
    expertReasoningTrace: [
      "Representar o problema com qualificadores semânticos.",
      "Escolher a síndrome guarda-chuva.",
      "Comparar diferenciais da mesma síndrome antes de fechar diagnóstico.",
    ],
    _revisar: "Rascunho gerado localmente pelo Codex; revisar conteúdo médico antes de publicar.",
  };
}

fs.mkdirSync("casos_gerados", { recursive: true });

const entidades = data.map(({ cid, entidade, sindrome, temaId, temaNome, area }) => ({
  cid,
  entidade,
  sindrome,
  incidencia: "alta",
  temaId,
  temaNome,
  area,
  prio: "Diamante",
}));

for (const item of data) {
  fs.writeFileSync(`casos_gerados/${item.cid}.json`, JSON.stringify(buildCase(item), null, 2));
}

fs.writeFileSync("entidades.json", JSON.stringify(entidades, null, 2));
fs.writeFileSync("temas_nao_clinicos.json", JSON.stringify(temasNaoClinicos, null, 2));
fs.writeFileSync("fila_revisar.json", JSON.stringify({
  generatedAt: new Date().toISOString(),
  revisar: data.map((item) => item.cid),
  invalidos: [],
  observacao: "Todos os 30 casos são rascunhos para revisão humana antes de publicação.",
}, null, 2));

console.log("Casos gerados:", data.length);
console.log("Temas não clínicos registrados:", temasNaoClinicos.length);
